### ISSUE TITLE
Error on launch server.py

### ISSUE THREAD

**Issue by sergeynosov13** [Kolhax/Vape-V4-Crack#2]
C:\Users\FyrekS\Desktop\Vape V4 Cracked>py server.py
Traceback (most recent call last):
  File "C:\Users\FyrekS\Desktop\Vape V4 Cracked\server.py", line 20, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\FyrekS\AppData\Roaming\Python\Python39\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\FyrekS\AppData\Roaming\Python\Python39\site-packages\OpenSSL\SSL.py", line 10, in <module>
    from OpenSSL._util import (
  File "C:\Users\FyrekS\AppData\Roaming\Python\Python39\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\FyrekS\AppData\Roaming\Python\Python39\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\FyrekS\AppData\Roaming\Python\Python39\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Не найдена указанная процедура.

**Comment by Kolhax** [comment]
read FAQ
> pip install pyOpenSSL --upgrade

**Comment by VASSERMAN521** [comment]
> read FAQ
> 
> > pip install pyOpenSSL --upgrade

I have an identical problem and this solution did not help me

**Comment by Kolhax** [comment]
use pyvenv (read the readme.md)
