### ISSUE TITLE
The problem when starting the server

### ISSUE THREAD

**Issue by VASSERMAN521** [Kolhax/Vape-V4-Crack#3]
I have not been able to find a solution to this problem on my own(

I use the command "python" instead of "py", because "py" in my case refers to python 3.12. Maybe this is the problem?

PS C:\Users\USER\Desktop\Vape-V4-Crack-main\Vape V4 Cracked> python server.py
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Vape-V4-Crack-main\Vape V4 Cracked\server.py", line 20, in <module>
    from OpenSSL import crypto, SSL
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\SSL.py", line 11, in <module>    from OpenSSL._util import (
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 15, in <module>
    from cryptography.exceptions import InternalError
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: Не найдена указанная процедура.
PS C:\Users\USER\Desktop\Vape-V4-Crack-main\Vape V4 Cracked> py server.py

**Comment by Kolhax** [comment]
read the common issues, simply :
```pip install --upgrade --force-reinstall pyOpenSSL```
and to select the py version you want simply:
```py -3.11 server.py``` for example to start with 3.11 (has to be installed aswell)
and if you want to avoid packages conflicts please use pyvenv
