### ISSUE TITLE
Starting the server

### ISSUE THREAD

**Issue by 1B4adr** [Kolhax/Vape-V4-Crack#4]
Loading mappings...
Loading cached fields...
Loading cached methods...
Loaded 1.7.10 mapping!
Loading mappings...
Loading cached fields...
Loading cached methods...
Loaded 1.8.9 mapping!
Loading mappings...
Loading cached fields...
Loading cached methods...
Loaded 1.12 mapping!
Passed integrity check!
Traceback (most recent call last):
  File "C:\Users\badrx\Vape-V4-Crack\Vape V4 Cracked\server.py", line 692, in <module>
    main()
  File "C:\Users\badrx\Vape-V4-Crack\Vape V4 Cracked\server.py", line 682, in main
    start_server = websockets.serve(
  File "C:\Users\badrx\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\asyncio\server.py", line 736, in __init__
    self.server = Server(
  File "C:\Users\badrx\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\asyncio\server.py", line 281, in __init__
    self.loop = asyncio.get_running_loop()
RuntimeError: no running event loop

**Comment by Kolhax** [comment]
will still work, downgrade python
